# Docker Compose configuration for Conduit
# For local development and testing

version: '3.8'

services:
  conduit:
    build:
      context: .
      dockerfile: Dockerfile
    image: conduit:latest
    container_name: conduit
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
    env_file:
      - .env
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3000/health', (r) => { process.exit(r.statusCode === 200 ? 0 : 1); })"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 5s
    # Security options
    security_opt:
      - no-new-privileges:true
    # Resource limits (adjust as needed)
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 512M
        reservations:
          cpus: '0.5'
          memory: 256M
